version: '3.9'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations account && python manage.py makemigrations searchjob && python manage.py migrate && python run.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/SearchJob/
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    env_file:
      - ./.env.dev

volumes:
  postgres_data: